// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  // 这样配置就可以在prisma 文件里面写入models 然后拆开，避免schema.prisma 写太多了
  schema: "prisma",
  // schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["PRISMA_DATABASE_URL"],
  },
});
